ALTER TABLE "App" ADD COLUMN "creditsPerUsd" INTEGER NOT NULL DEFAULT 100;

ALTER TABLE "CheckoutSession" ADD COLUMN "usdAmount" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "CheckoutSession" ADD COLUMN "creditsPerUsd" INTEGER NOT NULL DEFAULT 100;
