#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLATFORM_ENV_FILE="${ROOT_DIR}/.env.local"
DEMO_ENV_FILE="${ROOT_DIR}/.env.demo"
CONCURRENTLY_BIN="${ROOT_DIR}/node_modules/.bin/concurrently"

load_env_file() {
  local env_file="$1"

  if [ ! -f "${env_file}" ]; then
    return 0
  fi

  set -a
  # shellcheck disable=SC1090
  . "${env_file}"
  set +a
}

load_env_file "${PLATFORM_ENV_FILE}"
load_env_file "${DEMO_ENV_FILE}"

if [ ! -x "${CONCURRENTLY_BIN}" ]; then
  echo "Missing concurrently binary at ${CONCURRENTLY_BIN}. Run npm install first." >&2
  exit 1
fi

API_PORT="${API_PORT:-4100}"
WEB_PORT="${WEB_PORT:-3101}"
API_ORIGIN="${API_ORIGIN:-https://api.celeris.pro}"
PUBLIC_SITE_ORIGIN="${CELERIS_PUBLIC_SITE_ORIGIN:-https://celeris.pro}"
DEVELOPER_APP_ORIGIN="${CELERIS_DEVELOPER_APP_ORIGIN:-https://app.celeris.pro}"
DEMO_FRONTEND_ORIGIN="${CELERIS_DEMO_FRONTEND_ORIGIN:-https://demo.celeris.pro}"
HOSTED_AUTH_ORIGIN="${CELERIS_HOSTED_AUTH_ORIGIN:-https://auth.celeris.pro}"
NEXT_PUBLIC_API_ORIGIN_VALUE="${NEXT_PUBLIC_API_ORIGIN:-${API_ORIGIN}}"
NEXT_PUBLIC_SITE_ORIGIN_VALUE="${NEXT_PUBLIC_SITE_ORIGIN:-${PUBLIC_SITE_ORIGIN}}"
NEXT_PUBLIC_DEVELOPER_APP_ORIGIN_VALUE="${NEXT_PUBLIC_DEVELOPER_APP_ORIGIN:-${DEVELOPER_APP_ORIGIN}}"
NEXT_PUBLIC_DEMO_FRONTEND_ORIGIN_VALUE="${NEXT_PUBLIC_DEMO_FRONTEND_ORIGIN:-${DEMO_FRONTEND_ORIGIN}}"
NEXT_PUBLIC_HOSTED_AUTH_ORIGIN_VALUE="${NEXT_PUBLIC_HOSTED_AUTH_ORIGIN:-${HOSTED_AUTH_ORIGIN}}"
NEXT_PUBLIC_DEMO_APP_ID_VALUE="${NEXT_PUBLIC_DEMO_APP_ID:-}"
HELLO_CELERIS_PACKAGE_ID_VALUE="${HELLO_CELERIS_PACKAGE_ID:-}"
HELLO_CELERIS_APP_STATE_OBJECT_ID_VALUE="${HELLO_CELERIS_APP_STATE_OBJECT_ID:-}"
CELERIS_APP_ENCRYPTION_KEY_VALUE="${CELERIS_APP_ENCRYPTION_KEY:-development-celeris-app-encryption-key}"
CELERIS_GOOGLE_CLIENT_ID_VALUE="${CELERIS_GOOGLE_CLIENT_ID:-development-google-client-id}"
CELERIS_GOOGLE_CLIENT_SECRET_VALUE="${CELERIS_GOOGLE_CLIENT_SECRET:-development-google-client-secret}"
CELERIS_GOOGLE_REDIRECT_URI_VALUE="${CELERIS_GOOGLE_REDIRECT_URI:-https://api.celeris.pro/v1/auth/google/callback}"
CELERIS_GOOGLE_ISSUER_VALUE="${CELERIS_GOOGLE_ISSUER:-https://accounts.google.com}"
CELERIS_ZKLOGIN_SALT_SEED_VALUE="${CELERIS_ZKLOGIN_SALT_SEED:-development-celeris-zklogin-salt-seed}"
CELERIS_ZKLOGIN_PROVER_ORIGIN_VALUE="${CELERIS_ZKLOGIN_PROVER_ORIGIN:-http://localhost:9000}"
CELERIS_ZKLOGIN_MAX_EPOCH_WINDOW_VALUE="${CELERIS_ZKLOGIN_MAX_EPOCH_WINDOW:-2}"

exec "${CONCURRENTLY_BIN}" -n api,web,tunnel -c blue,green,magenta \
  "PORT=${API_PORT} API_ORIGIN=${API_ORIGIN} CELERIS_PUBLIC_SITE_ORIGIN=${PUBLIC_SITE_ORIGIN} CELERIS_DEVELOPER_APP_ORIGIN=${DEVELOPER_APP_ORIGIN} CELERIS_DEMO_FRONTEND_ORIGIN=${DEMO_FRONTEND_ORIGIN} CELERIS_HOSTED_AUTH_ORIGIN=${HOSTED_AUTH_ORIGIN} CELERIS_APP_ENCRYPTION_KEY=${CELERIS_APP_ENCRYPTION_KEY_VALUE} CELERIS_GOOGLE_CLIENT_ID=${CELERIS_GOOGLE_CLIENT_ID_VALUE} CELERIS_GOOGLE_CLIENT_SECRET=${CELERIS_GOOGLE_CLIENT_SECRET_VALUE} CELERIS_GOOGLE_REDIRECT_URI=${CELERIS_GOOGLE_REDIRECT_URI_VALUE} CELERIS_GOOGLE_ISSUER=${CELERIS_GOOGLE_ISSUER_VALUE} CELERIS_ZKLOGIN_SALT_SEED=${CELERIS_ZKLOGIN_SALT_SEED_VALUE} CELERIS_ZKLOGIN_PROVER_ORIGIN=${CELERIS_ZKLOGIN_PROVER_ORIGIN_VALUE} CELERIS_ZKLOGIN_MAX_EPOCH_WINDOW=${CELERIS_ZKLOGIN_MAX_EPOCH_WINDOW_VALUE} npm run dev --workspace @celeris/api" \
  "PORT=${WEB_PORT} NEXT_PUBLIC_API_ORIGIN=${NEXT_PUBLIC_API_ORIGIN_VALUE} NEXT_PUBLIC_SITE_ORIGIN=${NEXT_PUBLIC_SITE_ORIGIN_VALUE} NEXT_PUBLIC_DEVELOPER_APP_ORIGIN=${NEXT_PUBLIC_DEVELOPER_APP_ORIGIN_VALUE} NEXT_PUBLIC_DEMO_FRONTEND_ORIGIN=${NEXT_PUBLIC_DEMO_FRONTEND_ORIGIN_VALUE} NEXT_PUBLIC_HOSTED_AUTH_ORIGIN=${NEXT_PUBLIC_HOSTED_AUTH_ORIGIN_VALUE} NEXT_PUBLIC_DEMO_APP_ID=${NEXT_PUBLIC_DEMO_APP_ID_VALUE} HELLO_CELERIS_PACKAGE_ID=${HELLO_CELERIS_PACKAGE_ID_VALUE} HELLO_CELERIS_APP_STATE_OBJECT_ID=${HELLO_CELERIS_APP_STATE_OBJECT_ID_VALUE} npm run dev --workspace @celeris/web" \
  "npm run dev:tunnel"
