#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env.local"
CONCURRENTLY_BIN="${ROOT_DIR}/node_modules/.bin/concurrently"

load_local_env() {
  if [ ! -f "${ENV_FILE}" ]; then
    return 0
  fi

  set -a
  # shellcheck disable=SC1090
  . "${ENV_FILE}"
  set +a
}

load_local_env

if [ ! -x "${CONCURRENTLY_BIN}" ]; then
  echo "Missing concurrently binary at ${CONCURRENTLY_BIN}. Run npm install first." >&2
  exit 1
fi

API_PORT="${API_PORT:-4100}"
WEB_PORT="${WEB_PORT:-3101}"
API_ORIGIN="${API_ORIGIN:-https://api.celeris.pro}"
DEVELOPER_APP_ORIGIN="${CELERIS_DEVELOPER_APP_ORIGIN:-https://app.celeris.pro}"
DEMO_FRONTEND_ORIGIN="${CELERIS_DEMO_FRONTEND_ORIGIN:-https://demo.celeris.pro}"
HOSTED_AUTH_ORIGIN="${CELERIS_HOSTED_AUTH_ORIGIN:-https://auth.celeris.pro}"
NEXT_PUBLIC_API_ORIGIN_VALUE="${NEXT_PUBLIC_API_ORIGIN:-${API_ORIGIN}}"
NEXT_PUBLIC_DEVELOPER_APP_ORIGIN_VALUE="${NEXT_PUBLIC_DEVELOPER_APP_ORIGIN:-${DEVELOPER_APP_ORIGIN}}"
NEXT_PUBLIC_DEMO_FRONTEND_ORIGIN_VALUE="${NEXT_PUBLIC_DEMO_FRONTEND_ORIGIN:-${DEMO_FRONTEND_ORIGIN}}"
NEXT_PUBLIC_HOSTED_AUTH_ORIGIN_VALUE="${NEXT_PUBLIC_HOSTED_AUTH_ORIGIN:-${HOSTED_AUTH_ORIGIN}}"
CELERIS_APP_ENCRYPTION_KEY_VALUE="${CELERIS_APP_ENCRYPTION_KEY:-development-celeris-app-encryption-key}"
CELERIS_GOOGLE_CLIENT_ID_VALUE="${CELERIS_GOOGLE_CLIENT_ID:-development-google-client-id}"
CELERIS_GOOGLE_CLIENT_SECRET_VALUE="${CELERIS_GOOGLE_CLIENT_SECRET:-development-google-client-secret}"
CELERIS_GOOGLE_REDIRECT_URI_VALUE="${CELERIS_GOOGLE_REDIRECT_URI:-https://api.celeris.pro/v1/auth/google/callback}"
CELERIS_GOOGLE_ISSUER_VALUE="${CELERIS_GOOGLE_ISSUER:-https://accounts.google.com}"

exec "${CONCURRENTLY_BIN}" -n api,web,tunnel -c blue,green,magenta \
  "PORT=${API_PORT} API_ORIGIN=${API_ORIGIN} CELERIS_DEVELOPER_APP_ORIGIN=${DEVELOPER_APP_ORIGIN} CELERIS_DEMO_FRONTEND_ORIGIN=${DEMO_FRONTEND_ORIGIN} CELERIS_HOSTED_AUTH_ORIGIN=${HOSTED_AUTH_ORIGIN} CELERIS_APP_ENCRYPTION_KEY=${CELERIS_APP_ENCRYPTION_KEY_VALUE} CELERIS_GOOGLE_CLIENT_ID=${CELERIS_GOOGLE_CLIENT_ID_VALUE} CELERIS_GOOGLE_CLIENT_SECRET=${CELERIS_GOOGLE_CLIENT_SECRET_VALUE} CELERIS_GOOGLE_REDIRECT_URI=${CELERIS_GOOGLE_REDIRECT_URI_VALUE} CELERIS_GOOGLE_ISSUER=${CELERIS_GOOGLE_ISSUER_VALUE} npm run dev --workspace @celeris/api" \
  "PORT=${WEB_PORT} NEXT_PUBLIC_API_ORIGIN=${NEXT_PUBLIC_API_ORIGIN_VALUE} NEXT_PUBLIC_DEVELOPER_APP_ORIGIN=${NEXT_PUBLIC_DEVELOPER_APP_ORIGIN_VALUE} NEXT_PUBLIC_DEMO_FRONTEND_ORIGIN=${NEXT_PUBLIC_DEMO_FRONTEND_ORIGIN_VALUE} NEXT_PUBLIC_HOSTED_AUTH_ORIGIN=${NEXT_PUBLIC_HOSTED_AUTH_ORIGIN_VALUE} npm run dev --workspace @celeris/web" \
  "npm run dev:tunnel"
